[project]
name = 'Blockchain-Based-Tourism-Destination-Management-Systems'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.resource-allocation]
path = 'contracts/resource-allocation.clar'
clarity_version = 2
epoch = 2.5

[contracts.tourism-board-verification]
path = 'contracts/tourism-board-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
